repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0 # or the latest version of pylint you are using
    hooks:
      - id: pylint
        name: pylint
        language: system

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
