"""Initial migration

Revision ID: 9dc82bc010d1
Revises:
Create Date: 2025-02-06 20:43:36.198410

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9dc82bc010d1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
